# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - 'pypy3'

install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda


jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/flake8-dunder-all
        provider: pypi
        user: "DomDF"
        password:
          secure:
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        on:
          repo: domdfcoding/flake8-dunder-all
        provider: script
        script: .ci/travis_deploy_conda.sh || return 1;
